export const DELETE_DETAILORDER = "DELETE_DETAILORDER";
export const UPDATE_DETAILORDER = "UPDATE_DETAILORDER";
export const GET_DETAILORDERS = "GET_DETAILORDERS";
export const GET_DETAILORDER = "GET_DETAILORDER";
export const RESET = "RESET";